### ISSUE TITLE
xdebug?

### ISSUE THREAD

**Issue by danielzzz** [splitbrain/docker-phpfarm#10]
hi, I've seen you're adding xdebug to the build but somehow it doesn't appear in phpinfo()  
PHP Version 5.6.29-0+deb8u1

should I enable it somehow?

thx
regards, dan

**Comment by splitbrain** [comment]
that's not a version that should be in the image. it's a Debian packaged
php. are you sure you are running the PHP in the container?

**Comment by danielzzz** [comment]
hmm, you're right - I guess I must have messed up my nginx-proxy config. 
I checked out the direct connection to the container and it does show xdebug
thanks for the heads up!
dan
