### ISSUE TITLE
PHP DEBUG versions

### ISSUE THREAD

**Issue by inquam** [splitbrain/docker-phpfarm#11]
I noticed that the PHP versions built are DEBUG versions. I was going to use this for a local development image. So I modified it a bit. But how do I make it build RELEASE builds of PHP? I wanted to use Z-Ray with the supported versions but that doesn't work with DEBUG builds.

**Comment by splitbrain** [comment]
No idea what z-ray is. The builds include xdebug and enable it by default. I guess it should be possible to disable xdebug through a local php.ini as described in the documentation.

**Comment by inquam** [comment]
z-ray is a zend extension to php that gives you information about the request like function calls, memory consumption, db querys etc. http://www.zend.com/en/products/server/z-ray

x-debug doesn't require a debug build of PHP as far as I can recall? I have added it to non debug builds of php before. As far as I recall the debug information of php is only needed to debug php itself, when you work on the core for instance develop your own extensions etc.

**Comment by splitbrain** [comment]
Hmm I'm not explicitly enable any debug flags: https://github.com/splitbrain/docker-phpfarm/blob/master/phpfarm/custom-options.sh

And the options set by phpfarm do not to do either: https://github.com/cweiske/phpfarm/blob/master/src/options.sh

What makes you think they are compiled with debug symbols? Does phpinfo() mention it?

**Comment by inquam** [comment]
Running bash on the image and checking the versions of the built php versions.

> root@4d1efc6c58e2:/phpfarm/inst/php-5.6.29/bin# pwd
> /phpfarm/inst/php-5.6.29/bin
> root@4d1efc6c58e2:/phpfarm/inst/php-5.6.29/bin# ./php -v
> PHP 5.6.29 (cli) (built: Mar 10 2017 14:52:01) (DEBUG)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans

As you can see it's clearly marked as (DEBUG)

**Comment by splitbrain** [comment]
Hmm weird. I guess we need some --no-debug build flag or something? Pull request welcome.

**Comment by inquam** [comment]
No that doesn't seem to be a valid flag. The environment variable DEBUG can also make sure debug builds are built. But can't see that being set anywhere either.

**Comment by eugenesia** [comment]
I think the PHPFarm compile script is the one that inserted the `--enable-debug` flag? See https://github.com/cweiske/phpfarm/blob/master/src/compile.sh#L116

The configure `--enable-debug` flag compiles PHP with debugging symbols, according to http://php.net/manual/en/configure.about.php

**Comment by splitbrain** [comment]
That fork looks interesting. I'm looking into it right now... it does not work right out of the box as replacement, so I have to figure out what to adjust.

**Comment by splitbrain** [comment]
I just pushed a branch that makes use of the fork. Took me a while but it seems to work now. Could you try it before I merge it into master?

**Comment by inquam** [comment]
I'll check it out. I manually made it strip --enable-debug from the compile.sh script and that worked fine to. But I'll give your fork a go asap.

**Comment by eugenesia** [comment]
Thanks @splitbrain I tried the fpoirotte branch with Dockerfile-Jessie, it seems to work fine and indicates it's NOT a debug build:
```
root@3c002eedf6bb:/phpfarm/inst/php-5.3.29/bin# ./php --version
PHP 5.3.29 (cli) (built: Mar 22 2017 12:00:29)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

I'll try the Dockerfile-Wheezy version next.

**Comment by eugenesia** [comment]
Hi @splitbrain I tried the fpoirotte branch with Dockerfile-Wheezy. The build took a long time 😂  but I loaded _index.php_ for the different PHP versions and all reported NO debug build. I also tested with PHP CLI, see below.

```bash
root@11d77e36344b:/phpfarm/inst/php-5.2/bin# ./php --version
PHP 5.2.17 (cli) (built: Mar 23 2017 10:16:18)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans
```

I guess we're good to go?
