### ISSUE TITLE
Integrate with CircleCI

### ISSUE THREAD

**Issue by eugenesia** [splitbrain/docker-phpfarm#19]
Unable to integrate this project to CircleCI as I don't have admin access to this repo - see screenshot.

<img width="1023" alt="circleci_cannot_add_splitbrain_docker_phpfarm" src="https://user-images.githubusercontent.com/4341000/31125264-9fa1cc4e-a83f-11e7-8985-cb8a096ec962.png">

May need to contact CircleCI support for help.

**Comment by splitbrain** [comment]
Hmm it seems I can't make you admin. There's only collaborators. I guess admin is needed to install the webhook.

I set up the project myself: https://circleci.com/gh/splitbrain/docker-phpfarm/1

But it seems not to work. I'm not sure if I can invite you to the circleci project?

**Comment by eugenesia** [comment]
Hi @splitbrain did you invite me to the CircleCI project? It seems I can configure some variables.

I'll try to make it work and get back to you.

**Comment by splitbrain** [comment]
It might have done that automatically when I created the project and it found you as collaborator.

**Comment by splitbrain** [comment]
You're already collaborator there.

![splitbrain-phpfarm - docker hub](https://user-images.githubusercontent.com/86426/31232578-94e92c6e-a9ea-11e7-8950-9a9c4ec7bf50.png)

**Comment by splitbrain** [comment]
I guess the automated building at docker hub should be disabled?

**Comment by eugenesia** [comment]
Successfully integrated with CircleCI https://circleci.com/gh/splitbrain/docker-phpfarm . Thanks @splitbrain !

Not sure about the automated build. I think it auto-updates the description page from the Github repo's README though. It's not affecting the build process, maybe let's leave it?
