### ISSUE TITLE
xdebug in php 7.1

### ISSUE THREAD

**Issue by Odalrick** [splitbrain/docker-phpfarm#20]
According to the documentation xdebug should be active for php 7.1 but as far as I can tell it just isn't there. Not in phpinfo() or any config files, doesn't connect to the IDE, xdebug_break doesn't exist.

It there a mistake in the documentation or is https://hub.docker.com/r/splitbrain/phpfarm/ out of date or something else?

**Comment by Odalrick** [comment]
I just noticed that the builds have been failing for six months, maybe that has something to do with the problem-

**Comment by eugenesia** [comment]
Hi @Odalrick sorry @splitbrain and I are fixing the issue with the build. In the meantime maybe you can try a fork https://hub.docker.com/r/eugenesia/phpfarm

Make sure to come back to this repo soon as this will be the official one from now on.

**Comment by Odalrick** [comment]
Good to know, I'll just be using 7.0 for now probably, it suffices for my purposes.

**Comment by eugenesia** [comment]
Hi @Odalrick we fixed the build now so you can use the Docker image for this repo https://hub.docker.com/r/splitbrain/phpfarm/ . Can you try and tell us if it works for you?

**Comment by Odalrick** [comment]
Great, it works with 7.1 now. Good job.
