### ISSUE TITLE
how enable shorttag?

### ISSUE THREAD

**Issue by pedro151** [splitbrain/docker-phpfarm#21]
how enable short-tag?

**Comment by splitbrain** [comment]
see https://github.com/splitbrain/docker-phpfarm#loading-custom-phpini-settings

**Comment by arnoldgamboa** [comment]
For some reasons the Dec 12 2018 build date does not successfully scan the .php directory for ini files. Other previous builds does. I'm stuck right now actually. any idea how to make it work?

**Comment by arnoldgamboa** [comment]
https://www.evernote.com/l/AB3svfWp7F9Pmqn2vJK-vnLeJZTMEBF1rzY
