### ISSUE TITLE
virtual hosts

### ISSUE THREAD

**Issue by gponty** [splitbrain/docker-phpfarm#26]
Hi and thank you for your job !

How i can have multiple vhosts, like : 
xxx.localhost:8073
xxx.localhost:8072
yyy.localhost:8073
yyy.localhost:8072
etc...
For each website (xxx.localhost) documentRoot can change (like /var/www/xxx/public)

Thank you !

**Comment by splitbrain** [comment]
This is nothing you can do with docker alone. Vhosts require appropriate DNS on the client side.

I wonder what you're trying to achieve but you're probably not using this docker image for what it was intended for.
