### ISSUE TITLE
Error during "docker run"

### ISSUE THREAD

**Issue by AxelBriche** [splitbrain/docker-phpfarm#3]
Hello, I have an error when I use docker run:

In sudo:

> docker run --rm -t -i -e APACHE_UID=$UID -v $PWD:/var/www:rw -p 8052:8052 -p 8053:8053 -p 8054:8054 -p 8055:8055 -p 8056:8056 splitbrain/phpfarm
> useradd: UID 0 is not unique
> chown: invalid user: `wwwrun'
> /usr/sbin/apache2ctl: 87: ulimit: error setting limit (Operation not permitted)
> chown: invalid user:`wwwrun'

With basic user:

> docker run --rm -t -i -e APACHE_UID=$UID -v $PWD:/var/www:rw -p 8052:8052 -p 8053:8053 -p 8054:8054 -p 8055:8055 -p 8056:8056 splitbrain/phpfarm
> /usr/sbin/apache2ctl: 87: ulimit: error setting limit (Operation not permitted)
> apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6 for ServerName
> [Wed Mar 18 19:05:22 2015] [notice] Apache/2.2.22 (Debian) mod_fcgid/2.3.6 configured -- resuming normal operations

Why please ? Thanks.

**Comment by splitbrain** [comment]
Sorry I can not reproduce this. What is your $UID?
