### ISSUE TITLE
Link Data into Container, instead copy it

### ISSUE THREAD

**Issue by suther** [splitbrain/docker-phpfarm#5]
In your Dockerfile you use: 

COPY var-www /var/www/
COPY apache  /etc/apache2/
 
to copy the Files into your Dockerfile. Maybe it's better to use Volumes to link the Data of your Project-Dir to your Dockerfile: https://docs.docker.com/userguide/dockervolumes/

Using a Volume makes you able to access to the same Data from different Images at the same time.

**Comment by thaJeztah** [comment]
The files added here are just the "default" files. However, there are a number of things to consider here;

- During *development*, yes, using a volume is often the way to go; you can edit the source files outside of the container, and can see the changes without having to rebuild the image, and start a new container
- For production / deployment, you should *copy* the source files into the image. The image can be pushed to Docker Hub (or built using automated build), basically, you're "packaging" a new release in an image, and deploy that image to the production server(s).

Volumes should be used for data that needs to persist after a container is deleted (which is, for example, when a container is replaced with a newer version / release). Examples of things that should be put in a volume are database data, uploads, etc.
